# Generated by Django 3.2.13 on 2023-02-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
