# Generated by Django 4.1.6 on 2023-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learning_subject",
            field=models.ManyToManyField(
                related_name="learning_user", to="routine.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
